config/routes.rb
Blogasaurus::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts do
    get 'archive/:year(/:month)', action: 'archive', on: :collection, as: :archive
  end
  resources :authors
  resources :categories
  resources :tags
  resources :comments
  root to: 'posts#index'
end

app/models/blogasaurus/ability.rb
module Blogasaurus
  class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= Blogasaurus.user_class.new # guest user (not logged in)
      if user.try :admin?
        can :manage, :all
      else
        can :show, [Category, Tag, Author]
        can :read, Post, ['blogasaurus_posts.published = ? AND blogasaurus_posts.category_id IS NOT NULL AND blogasaurus_posts.created_at < ?', true, Time.now] do |post|
          post.created_at <= Time.now and post.category != nil
        end
        can :create, Comment
      end
    end
  end
end

app/models/blogasaurus/author.rb
module Blogasaurus
  class Author < ActiveRecord::Base

    include Blogasaurus::Concerns::Sluggable

    has_many :posts

    validates :bio, :photo, :title, presence: true

    has_attached_file :photo,
                      styles: {
                        small: ['70x70^', :jpg],
                        large: ['300', :jpg]
                      },
                      convert_options: {
                        small: '-gravity center -extent 70x70'
                      }
    validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png)

    # nullifying the blogs would be bad, so we have to assign them to someone else.
    after_destroy do
      blogs.update_all blog_author: BlogAuthor.first
    end

    def to_s
      title
    end
  end
end

app/models/blogasaurus/category.rb
module Blogasaurus
  class Category < ActiveRecord::Base
    include Blogasaurus::Concerns::Sluggable

    has_many :posts, dependent: :nullify # let the associated records go, so they can be re-categoriezed

    validates :title, :description, presence: true

    has_attached_file :photo, styles: {thumb: ['200x200^', :jpg]}, convert_options: {thumb: '-gravity center -extent 200x200'}

    def to_s
      title
    end
  end
end

app/models/blogasaurus/comment.rb
module Blogasaurus
  class Comment < ActiveRecord::Base
    belongs_to :post

    validates :post, :email, :name, :text, presence: true
    validates :email, format: {with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i}, allow_blank: true

    before_validation do
      self.email = email.downcase
    end

    def gravatar_url
      require 'digest/md5'
      hash = Digest::MD5.hexdigest(email)
      "http://www.gravatar.com/avatar/#{hash}"
    end
  end
end

app/models/blogasaurus/concerns/sluggable.rb
module Blogasaurus::Concerns::Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :create_slug
  end

  def create_slug
    if title && slug.blank?
      self.slug = title.parameterize
    end
  end

  def to_param
    "#{id}-#{slug}"
  end
end

app/models/blogasaurus/image.rb
module Blogasaurus
  class Image < ActiveRecord::Base
    belongs_to :post

    default_scope lambda { order(:position).order(:id) }

    has_attached_file :file,
                      styles: {large: ['700', :jpg], medium: ['300x300', :jpg], small: ['120x120^', :jpg]},
                      convert_options: {small: '-gravity center -extent 120x120'}
    validates_attachment_content_type :file, :content_type => %w(image/jpeg image/jpg image/png)

    def url(size = nil)
      file.url size
    end
  end
end

app/models/blogasaurus/post.rb
module Blogasaurus
  class Post < ActiveRecord::Base

    include Blogasaurus::Concerns::Sluggable

    belongs_to :author
    belongs_to :category
    has_many :tag_refs, dependent: :destroy
    has_many :tags, through: :tag_refs
    has_many :comments, dependent: :destroy

    has_many :images
    accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :missing_image

    validates :author, :category, :full_text, :intro_text, :title, presence: true

    # we don't want any categoryless records in here.
    scope :published, -> { where(published: true) }

    default_scope { order 'created_at DESC' }

    paginates_per 10

    def self.search(term)
      like = Rails.env.production? ? 'ILIKE' : 'LIKE'
      where("title #{like} :term OR intro_text #{like} :term OR full_text #{like} :term", term: "%#{term}%")
    end

    def tag_id_list=(ids)
      self.tags = ids.reject {|id| id.blank? }.map { |id| Tag.find id }
    end
    def tag_id_list
      tags.map {|tag| tag.id}
    end

    def day
      created_at.day
    end
    def month
      Date::ABBR_MONTHNAMES[created_at.month] + '.'
    end
    def image
      images.first.try :file
    end
    def needs_gallery?
      images.length > 1
    end
    def missing_image(params)
      params[:file].blank? && params[:alt].blank? && params[:position].blank? && params[:_destroy] == '0'
    end
  end
end

app/models/blogasaurus/tag.rb
module Blogasaurus
  class Tag < ActiveRecord::Base
    before_save { self.slug = '' } # clear out the slug so it is always updated

    include Blogasaurus::Concerns::Sluggable

    has_many :tag_refs, dependent: :destroy
    has_many :posts, through: :tag_refs

    validates :title, presence: true, uniqueness: true
  end
end

app/models/blogasaurus/tag_ref.rb
module Blogasaurus
  class TagRef < ActiveRecord::Base
    belongs_to :post
    belongs_to :tag
  end
end

app/controllers/blogasaurus/application_controller.rb
module Blogasaurus
  class ApplicationController < ::ApplicationController
    def current_ability
      @current_ability ||= Blogasaurus::Ability.new(current_user)
    end
  end
end

app/controllers/blogasaurus/authors_controller.rb
require_dependency "blogasaurus/application_controller"

module Blogasaurus
  class AuthorsController < ApplicationController
    before_action :set_author, only: :create
    load_and_authorize_resource

    layout 'layouts/blogasaurus/admin', except: :show

    # GET /blog_authors
    # GET /blog_authors.json
    def index
    end

    # GET /blog_authors/1
    # GET /blog_authors/1.json
    def show
      @posts = @author.posts.accessible_by(current_ability).page(params[:page])
    end

    # GET /blog_authors/new
    def new
    end

    # GET /blog_authors/1/edit
    def edit
    end

    # POST /blog_authors
    # POST /blog_authors.json
    def create
      respond_to do |format|
        if @author.save
          format.html { redirect_to @author, notice: 'Author was successfully created.' }
          format.json { render action: 'show', status: :created, location: @author }
        else
          format.html { render action: 'new' }
          format.json { render json: @author.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /blog_authors/1
    # PATCH/PUT /blog_authors/1.json
    def update
      respond_to do |format|
        if @author.update(author_params)
          format.html { redirect_to @author, notice: 'Author was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @author.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /blog_authors/1
    # DELETE /blog_authors/1.json
    def destroy
      @author.destroy
      respond_to do |format|
        format.html { redirect_to authors_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_author
        @author = Author.new author_params
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def author_params
        params.require(:author).permit(:title, :photo, :bio)
      end
  end
end

app/controllers/blogasaurus/categories_controller.rb
require_dependency "blogasaurus/application_controller"

module Blogasaurus
  class CategoriesController < ApplicationController
    before_action :set_category, only: :create
    load_and_authorize_resource

    layout 'layouts/blogasaurus/admin', except: :show

    # GET /blog_categories
    # GET /blog_categories.json
    def index
    end

    # GET /blog_categories/1
    # GET /blog_categories/1.json
    def show
      @posts = @category.posts.accessible_by(current_ability).page(params[:page])
    end

    # GET /blog_categories/new
    def new
    end

    # GET /blog_categories/1/edit
    def edit
    end

    # POST /blog_categories
    # POST /blog_categories.json
    def create
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render action: 'show', status: :created, location: @category }
        else
          format.html { render action: 'new' }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /blog_categories/1
    # PATCH/PUT /blog_categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /blog_categories/1
    # DELETE /blog_categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.new category_params
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(:title, :description)
      end
  end
end

app/controllers/blogasaurus/comments_controller.rb
require_dependency "blogasaurus/application_controller"

module Blogasaurus
  class CommentsController < ApplicationController
    before_action :set_comment, only: :create
    load_and_authorize_resource

    def create
      @post = @comment.post
      if verify_recaptcha(model: @comment, message: 'Recaptcha invalid') and @comment.save
        flash[:success] = 'Comment created successfully'

        redirect_to @post
      else
        flash.now[:error] = 'There was an error creating your comment.'
        render 'blogasaurus/posts/show'
      end
    end
    def destroy
      @post = @comment.post
      @comment.destroy
      flash[:success] = 'Comment deleted'
      redirect_to @post
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = Comment.new comment_params
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def comment_params
        params.require(:comment).permit(:name, :text, :email, :post_id)
      end
  end
end

app/controllers/blogasaurus/old_blogs_controller.rb
require_dependency "blogasaurus/application_controller"

module Blogasaurus
  class BlogsController < ApplicationController
    load_and_authorize_resource

    def index
    end

    def new
      @blog = Blog.new
    end
  end
end

app/controllers/blogasaurus/posts_controller.rb
require_dependency "blogasaurus/application_controller"

module Blogasaurus
  class PostsController < ApplicationController
    before_action :set_post, only: :create
    before_action :set_post_optional, only: :new
    load_and_authorize_resource

    layout 'blogasaurus/admin', except: [:index, :show]

    # GET /posts
    # GET /posts.json
    def index
      if params[:search_term]
        @posts = @posts.search(params[:search_term]).page(params[:page])
      else
        @posts = @posts.page(params[:page])
      end
    end

    def archive
      redirect_to posts_path if params[:year].blank?
      if params[:month].blank?
        start_date = Time.new params[:year].to_i
        end_date = start_date + 1.year
      else
        start_date = Time.new params[:year].to_i, params[:month].to_i
        end_date = start_date + 1.month
      end
      @posts = @posts.where('created_at > ?', start_date).where('created_at < ?', end_date).page(params[:page])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @comment = @post.comments.build
    end

    # GET /posts/new
    def new
      5.times do
        @post.images.build
      end
    end

    # GET /posts/1/edit
    def edit
      5.times do
        @post.images.build
      end
    end

    # POST /posts
    # POST /posts.json
    def create
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render action: 'show', status: :created, location: @post }
        else
          format.html { render action: 'new' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.new post_params
      end

      def set_post_optional
        if params.has_key? :post
          set_post
        else
          @post = Post.new
        end
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit :intro_text,
                                     :full_text,
                                     :author_id,
                                     :category_id,
                                     :image,
                                     :title,
                                     :created_at,
                                     {images_attributes: [:id, :file, :position, :alt, :_destroy]},
                                     {tag_id_list: []},
                                     :published
      end
  end
end

app/controllers/blogasaurus/tags_controller.rb
require_dependency "blogasaurus/application_controller"

module Blogasaurus
  class TagsController < ApplicationController
    before_action :set_tag, only: :create
    load_and_authorize_resource

    layout 'layouts/blogasaurus/admin', except: :show

    # GET /tags
    # GET /tags.json
    def index
    end

    # GET /tags/1
    # GET /tags/1.json
    def show
      @posts = @tag.posts.accessible_by(current_ability).page(params[:page])
    end

    # GET /tags/new
    def new
    end

    # GET /tags/1/edit
    def edit
    end

    # POST /tags
    # POST /tags.json
    def create
      respond_to do |format|
        if @tag.save
          format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
          format.json { render action: 'show', status: :created, location: @tag }
        else
          format.html { render action: 'new' }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /tags/1
    # PATCH/PUT /tags/1.json
    def update
      respond_to do |format|
        if @tag.update(tag_params)
          format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /tags/1
    # DELETE /tags/1.json
    def destroy
      @tag.destroy
      respond_to do |format|
        format.html { redirect_to tags_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_tag
        @tag = Tag.new tag_params
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def tag_params
        params.require(:tag).permit(:title)
      end
  end
end

app/helpers/blogasaurus/application_helper.rb
module Blogasaurus
  module ApplicationHelper
  end
end

app/helpers/blogasaurus/blogs_helper.rb
module Blogasaurus
  module BlogsHelper
  end
end

app/helpers/blogasaurus/posts_helper.rb
module Blogasaurus
  module PostsHelper
    def get_recent_posts(count = 3)
      Post.accessible_by(current_ability).limit count
    end
    def get_posts_grouped_by_year
      Post.accessible_by(current_ability).group_by do |p|
        p.created_at.beginning_of_year
      end
    end
    def get_posts_grouped_by_month
      Post.accessible_by(current_ability).group_by do |p|
        p.created_at.beginning_of_month
      end
    end
  end
end

app/views/blogasaurus/posts/_form.html.haml
= form_for @post do |f|
  = render partial: 'blogasaurus/shared/errors', object: f.object
  .row
    .col-md-4
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :slug
        = f.text_field :slug, class: 'form-control'
      .form-group
        = f.label :published
        .radio
          = f.label :published, value: true, class: 'radio-inline' do
            = f.radio_button :published, true
            Yes
          = f.label :published, value: false, class: 'radio-inline' do
            = f.radio_button :published, false
            No
      .form-group
        = f.label :created_at, 'Publish On'
        %p= f.date_select :created_at
      .form-group
        = f.label :author_id
        = f.collection_select :author_id, Blogasaurus::Author.all, :id, :title, {}, class: 'form-control chosen'
      .form-group
        = f.label :category_id
        = f.collection_select :category_id, Blogasaurus::Category.all, :id, :title, {}, class: 'form-control chosen'
      .form-group
        = f.label :tag_id_list, 'Tags'
        = f.collection_select :tag_id_list, Blogasaurus::Tag.all, :id, :title, {}, class: 'form-control chosen', multiple: true
    .col-md-8
      .form-group
        = f.label :intro_text
        = f.cktext_area :intro_text, class: 'form-control'
      .form-group
        = f.label :full_text
        = f.cktext_area :full_text, class: 'form-control'
      %table.table
        %thead
          %tr
            %th Image
            %th ALT
            %th Position
            %th Destroy
        %tbody
          = f.fields_for :images do |ff|
            %tr
              %td
                = ff.hidden_field :id
                - if ff.object.persisted?
                  = image_tag ff.object.url(:small)
                - else
                  = ff.file_field :file
              %td= ff.text_field :alt, class: 'form-control'
              %td= ff.text_field :position, class: 'form-control'
              %td= ff.check_box :_destroy
  = f.submit

app/views/blogasaurus/posts/_post.html.haml
.item
  .row
    .col-md-2
      .date
        .day= post.day
        .month= post.month
    .col-md-10
      %h2= post.title
      - unless post.published
        .alert.alert-danger Not Published
      - else
        - if Time.now < post.created_at
          .alert.alert-warning Scheduled to publish in the future
      = post.intro_text.html_safe
      %p
        .pull-left= link_to 'Read More', post, class: 'button button-blue'
        .clr
      - if can? :manage, post
        %p
          = link_to 'edit', edit_post_path(post), class: 'btn btn-xs btn-primary'
          = link_to 'delete', post, method: 'delete', class: 'btn btn-xs btn-danger', data: {confirm: 'Are you sure?'}
      %hr

app/views/blogasaurus/posts/_sidebar.html.haml
.h2 Categories
- Blogasaurus::Category.all.each do |category|
  %p= link_to category.title, category
.h2 Tags
- Blogasaurus::Tag.all.each do |tag|
  %p= link_to tag.title, tag

app/views/blogasaurus/posts/archive.html.haml
%h1
  Blog Archive:
  - if params[:month].blank?
    = params[:year]
  - else
    #{Date::MONTHNAMES[params[:month].to_i]} #{params[:year]}
- if can? :create, Blogasaurus::Post
  .well
    = link_to 'Create Post', new_post_path, class: 'btn btn-success'
.blog-items=render @posts
= paginate @posts

app/views/blogasaurus/posts/edit.html.haml
%h1 Editing Post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/blogasaurus/posts/index.html.haml
%h1 Welcome to our blog
- if can? :create, Blogasaurus::Post
  .well
    = link_to 'Create Post', new_post_path, class: 'btn btn-success'
.blog-items=render @posts
= paginate @posts

app/views/blogasaurus/posts/new.html.haml
%h1 New Post

= render 'form'

= link_to 'Back', posts_path

app/views/blogasaurus/posts/show.html.haml
.blog
  %h1= @post.title
  .byline
    = @post.created_at.strftime('%B %e, %Y')
    \|
    = link_to @post.category.title, @post.category
  = @post.intro_text.html_safe
  - if @post.images.any?
    - if @post.needs_gallery?
      .gallery
        .frame
        .images
          - @post.images.each do |image|
            = link_to image_tag(image.url(:small)), image.url(:large)
          .clr
    - else
      .blog-img= image_tag @post.image.url(:medium)
  = @post.full_text.html_safe
  .author
    .author-image= image_tag @post.author.photo.url(:small)
    .author-bio
      = link_to @post.author.title, @post.author
      = @post.author.bio.html_safe
  .comments
    %hr
    %h2 Comments
    - @post.comments.each do |comment|
      - next unless comment.persisted?
      .comment
        .name= comment.name
        .when= time_ago_in_words(comment.created_at) + ' ago'
        .image= image_tag comment.gravatar_url
        .body
          %p= comment.text
          - if can? :manage, comment
            %p= link_to 'delete', comment, method: 'delete', data: {confirm: 'Are you sure?'}
        .clr
    .form
      = form_for @comment do |f|
        = render partial: 'blogasaurus/shared/errors', object: f.object
        = f.hidden_field :post_id
        .row-fluid
          .col-md-6
            .field
              = f.label :name
              = f.text_field :name
          .col-md-6
            .field
              = f.label :email
              = f.text_field :email
        .field
          = f.label :text, 'Comment'
          = f.text_area :text, rows: 3
        .field= recaptcha_tags display: {theme: 'clean'}
        = f.submit 'Post Comment'